name: Nightly

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-linux-nightly-artifact:
    name: Nightly Artifact Linux Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          rpm \
          openjdk-17-jdk \
          openjdk-17-jdk-headless

      - name: show java version
        run:  type -a java;java -version

      - name: set java version
        run:  sudo update-java-alternatives -s java-1.17.0-openjdk-amd64

      - name: show java version
        run:  type -a java;java -version

      - name: build package
        run:  id;pwd;ls -al;./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64 packageReleaseDistributionForCurrentOS

      - name: build jar
        run:  id;pwd;ls -al;./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64 clean packageReleaseUberJarForCurrentOS


